#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f2f72e2e-3055-41bf-81a6-d2e32ba0ae8a

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String receivedData;
  int check;
  int volt1;
  int volt2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

// VEGA_SoftwareSerial - Version: Latest
#include <SoftwareSerial.h>
// #include <WiFiNINA.h>

// SomeSerial - Version: Latest
#include <SomeSerial.h>

// CurieSoftwareSerial for arc32 - Version: Latest
// #include <SoftwareSerial.h>

// CurieSoftwareSerial for arc32 - Version: Latest
// #include <SoftwareSerial.h>
// #include "SoftwareSerial.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/1a105c6a-a0bc-4208-b1e9-259305a503ff

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float voltage2;
  int volt;
  int voltage1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
// #include "many_to_one_data_read_.ino"
//#include<ModbusIP_ESP8266.h>
// Define the number of Arduinos sending data
const int numArduinos = 2;

// Define the Serial objects for communication with each Arduino
SoftwareSerial arduinoSerial[numArduinos] = {
  SoftwareSerial(D1, D2), // RX pin for Arduino 1, TX pin for Arduino 1
  SoftwareSerial(D3, D4), // RX pin for Arduino 2, TX pin for Arduino 2
  //  SoftwareSerial(D5, D6)  // RX pin for Arduino 3, TX pin for Arduino 3
};

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  for (int i = 0; i < numArduinos; i++) {
    arduinoSerial[i].begin(9600);
  }
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();
  // Defined in thingProperties.h

  // Connect to Arduino IoT Cloud

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
}
// int voltage1,voltage2;
void loop() {
  ArduinoCloud.update();
  // Your code here
  for (int i = 0; i < numArduinos; i++) {
    if (arduinoSerial[i].available()) {
      
      // receivedData.trim();
      check = i;
      Serial.print("Data from Arduino ");
      Serial.print(i + 1);
      Serial.print(": ");
      if (i % 2 == 0)
      {
        volt1 = arduinoSerial[i].parseInt();
        Serial.println(volt1);

      }
      else {
        // volt2 =arduinoSerial[i].parseInt();
        Serial.println(volt2);

      }
      // delay(500);
    }
  }


}







/*
  Since Volt1 is READ_WRITE variable, onVolt1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onVolt1Change()  {
  // Add your code here to act upon Volt1 change
  int temp = volt1;
  volt1 = temp;
}

/*
  Since Volt2 is READ_WRITE variable, onVolt2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onVolt2Change()  {
  // Add your code here to act upon Volt2 change
  int temp = volt2;
  volt2 = temp;
}

/*
  Since RecievedData is READ_WRITE variable, onRecievedDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRecievedDataChange()  {
  // Add your code here to act upon RecievedData change
}

/*
  Since ReceivedData is READ_WRITE variable, onReceivedDataChange() is
  executed every time a new value is received from IoT Cloud.
*/

/*
  Since ReceivedData is READ_WRITE variable, onReceivedDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onReceivedDataChange()  {
  // Add your code here to act upon ReceivedData change
}
/*
  Since Check is READ_WRITE variable, onCheckChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCheckChange()  {
  // Add your code here to act upon Check change
}