// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "514b3598-2c47-4dfe-9070-156c2188bae0";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onReceivedDataChange();
void onCheckChange();
void onVolt1Change();
void onVolt2Change();

String receivedData;
int check;
int volt1;
int volt2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(receivedData, READWRITE, ON_CHANGE, onReceivedDataChange);
  ArduinoCloud.addProperty(check, READWRITE, ON_CHANGE, onCheckChange);
  ArduinoCloud.addProperty(volt1, READWRITE, ON_CHANGE, onVolt1Change, 1);
  ArduinoCloud.addProperty(volt2, READWRITE, ON_CHANGE, onVolt2Change, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
